# Generated by Django 5.0.7 on 2024-08-03 11:00

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kebabspot',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='kebabspot',
            name='longitude',
        ),
        migrations.AddField(
            model_name='kebabspot',
            name='camping_places',
            field=models.BooleanField(default=False, verbose_name='Місце для кемпінгу'),
        ),
        migrations.AddField(
            model_name='kebabspot',
            name='gazebos',
            field=models.BooleanField(default=False, verbose_name='Альтанки'),
        ),
        migrations.AddField(
            model_name='kebabspot',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='SRID=4326;POINT(30.5234 50.4501)', srid=4326, verbose_name='Розташування'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kebabspot',
            name='notes',
            field=models.TextField(blank=True, default=False, verbose_name='Замітки'),
        ),
        migrations.AddField(
            model_name='kebabspot',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='Парковка'),
        ),
        migrations.AddField(
            model_name='kebabspot',
            name='payed_or_free',
            field=models.BooleanField(default=False, verbose_name='Платно чи безкоштовно'),
        ),
        migrations.AddField(
            model_name='kebabspot',
            name='place_for_fire',
            field=models.BooleanField(default=False, verbose_name='Облаштоване місце для багаття'),
        ),
        migrations.AddField(
            model_name='kebabspot',
            name='private_property',
            field=models.BooleanField(default=False, verbose_name='Приватна територія'),
        ),
        migrations.AddField(
            model_name='kebabspot',
            name='swimming_spot',
            field=models.BooleanField(default=False, verbose_name='Місце для купання'),
        ),
        migrations.AddField(
            model_name='kebabspot',
            name='tables',
            field=models.BooleanField(default=False, verbose_name='Столи'),
        ),
        migrations.AddField(
            model_name='kebabspot',
            name='toilets',
            field=models.BooleanField(default=False, verbose_name='Туалети'),
        ),
        migrations.AddField(
            model_name='kebabspot',
            name='trash_bins',
            field=models.BooleanField(default=False, verbose_name='Наявність смітників'),
        ),
        migrations.AlterField(
            model_name='kebabspot',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем'),
        ),
        migrations.AlterField(
            model_name='kebabspot',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва'),
        ),
        migrations.CreateModel(
            name='KebabSpotPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='kebab_spots/')),
                ('kebab_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.kebabspot')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('kebab_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='main.kebabspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'kebab_spot')},
            },
        ),
    ]
