# Generated by Django 5.0.7 on 2024-08-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_kebabspot_latitude_remove_kebabspot_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kebabspot',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Замітки'),
        ),
    ]
