# Generated by Django 5.0.7 on 2024-08-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_kebabspot_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kebabspot',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Назва'),
        ),
    ]
