# Generated by Django 5.0.7 on 2024-09-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_is_positive_commentrating_vote_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentrating',
            old_name='vote_type',
            new_name='is_positive',
        ),
    ]
