# Generated by Django 5.0.7 on 2024-09-17 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_vote_type_commentrating_is_positive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kebabspot',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Приховано'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст скарги')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kebab_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='main.kebabspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Скарга',
                'verbose_name_plural': 'Скарги',
            },
        ),
    ]
