# Generated by Django 5.0.7 on 2024-09-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_kebabspot_hidden_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='kebabspot',
            name='complaints_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість скарг'),
        ),
    ]
