# Generated by Django 5.0.7 on 2024-09-17 12:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_kebabspot_complaints_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='complaint',
            unique_together={('kebab_spot', 'user')},
        ),
    ]
