# Generated by Django 5.0.7 on 2024-10-01 12:12

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_complaint_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kebabspot',
            options={'verbose_name': 'Kebab spot', 'verbose_name_plural': 'Kebab spots'},
        ),
        migrations.AlterField(
            model_name='kebabspot',
            name='camping_places',
            field=models.BooleanField(default=False, verbose_name='Camping places'),
        ),
        migrations.AlterField(
            model_name='kebabspot',
            name='complaints_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Complaints count'),
        ),
        migrations.AlterField(
            model_name='kebabspot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='kebabspot',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='kebabspot',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='kebabspot',
            name='gazebos',
            field=models.BooleanField(default=False, verbose_name='Gazebos'),
        ),
        migrations.AlterField(
            model_name='kebabspot',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Hidden'),
        ),
        migrations.AlterField(
            model_name='kebabspot',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='kebabspot',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='kebabspot',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='kebabspot',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='Parking'),
        ),
        migrations.AlterField(
            model_name='kebabspot',
            name='payed_or_free',
            field=models.BooleanField(default=False, verbose_name='Paid or free of charge'),
        ),
        migrations.AlterField(
            model_name='kebabspot',
            name='place_for_fire',
            field=models.BooleanField(default=False, verbose_name='Place for fire'),
        ),
        migrations.AlterField(
            model_name='kebabspot',
            name='private_property',
            field=models.BooleanField(default=False, verbose_name='Private property'),
        ),
        migrations.AlterField(
            model_name='kebabspot',
            name='swimming_spot',
            field=models.BooleanField(default=False, verbose_name='Swimming spot'),
        ),
        migrations.AlterField(
            model_name='kebabspot',
            name='tables',
            field=models.BooleanField(default=False, verbose_name='Tables'),
        ),
        migrations.AlterField(
            model_name='kebabspot',
            name='toilets',
            field=models.BooleanField(default=False, verbose_name='Toilets'),
        ),
        migrations.AlterField(
            model_name='kebabspot',
            name='trash_bins',
            field=models.BooleanField(default=False, verbose_name='Trash bins'),
        ),
        migrations.AlterField(
            model_name='kebabspot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
