# Generated by Django 5.0.7 on 2024-10-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivationToken',
        ),
    ]
